[en]
  languageCode = "en"
  languageName = "English"
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  # contentDir = "content/en"

# Uncomment for multilingual sites, and customize the following config.
[bn]
   languageCode = "bn"
   languageName = "বাংলা"
   contentDir = "content/bn"
   title = "বাংলা"