baseURL = "http://mirwasi.co.uk"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Mir Wasi Ahmed"
title = "Mir Wasi Ahmed"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© 2021 - Mir Wasi Ahmed"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-153851003-1"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["tech","programming","software engineering","london", "uk"]

	# Add meta description in head part
	description = "Mir Wasi Ahmed - Software Engineer based in London"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Mir Wasi Ahmed"

	# Add a subtitle to your website
	subtitle = "Software Engineer based in London"

	# Activate to show authors on pages if available
	#listAuthor = false

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	# avatar = "/img/vitae.jpg"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "mwasiav"

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[menu.main]]
name = "Links"
url = "/links"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5


# Social Menu
[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://www.twitter.com/wasiahmed"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
